# Generated by Django 3.2.3 on 2021-05-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_device_pressuresensor_tempraturesensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempratureSensor',
            new_name='TemperatureSensor',
        ),
    ]
